services:

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureuka
    ports:
      - "8761:8761"
    networks:
      - app-network

  apigateway:
    build:
      context: ./APIGateway
    container_name: apigateway
    ports:
      - "8093:8093"
    depends_on:
      - eureka-server
    networks:
      - app-network

  candidature:
    build:
      context: ./Candidature
    container_name: mscandidature
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - app-network

  projet:
    build:
      context: ./Projet
    container_name: msprojet
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - app-network
  reclamation:
    build:
      context: ./Reclamation
    container_name: msreclamation
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - app-network


  meeting:
    build:
      context: ./Meeting
    container_name: msmeeting
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - app-network

  offre:
    build:
      context: ./Offre
    container_name: msoffre
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
